### ISSUE TITLE
"Shot skills", Super Tackle

### ISSUE THREAD

**Issue by Manitary** [Loreinator/Shuffle-Move#281] opened 2017-04-25 23:00 UTC
Among the new skills, these 2 may need some coding from you:

Barrier/Block/Rock Shot: removes 2 barriers/blocks/rocks, and (if successful) deals 2x damage. Boosting the skill increases the bonus damage. So it's a mix of Barrier Bash (skill level increases the damage), but with bonus damage even at SL1, which I don't know how to handle in the code.

Super Tackle: 4-matches deals increased damage. The problem here is that, unlike Po4/Po4+/4Up, skill boosting increases the rates, so I think that with the current code it would get an increase on all match sizes instead of just 4.

p.s.: I committed the stuff I already wrote for the update [here](https://github.com/Manitary/Shuffle-Move/commit/e2ed91961946f58f1e79abbc7a6bc8e9fef7ee1f), I'll make the request after I get more boards, and confirmations about some skills.

**Comment by Loreinator** [comment] 2017-04-29 16:04
I've implemented SUPER_TACKLE on the main branch. Basically, to enforce that the odds only go above 0 for a 4-match, use this code snippet:

```
      @Override
      protected double getOdds(SimulationTask task, ActivateComboEffect e) {
         if (e.getNumBlocks() == 4) {
            return super.getOdds(task, e);
         } else {
            return 0;
         }
      }
```

**Comment by Loreinator** [comment] 2017-04-29 16:11
Regarding the Barrier/Block/Rock Shot skills, you can just increase the base multiplier to 200. The rest of the code should work more-or-less by copying it from the other skills.

For example, ROCK_BREAK:
STRING ROCK_BREAK 100 100 100 100 150 170 180 200 MULT
Can be converted to ROCK_SHOT by, for example, multiplying the multipliers by 2:
STRING ROCK_BREAK 100 100 100 200 300 340 360 400 MULT

As for the code side, that "canActivate" not only controls activation, but score. If there are no blocks to erase, the multiplier won't take effect. It should work without any special handling beyond what is already done for the ROCK_BREAK, etc. effects.

**Comment by Manitary** [comment] 2017-05-10 11:44
Super Tackle works fine, it will get an update since the multiplier was wrong.

Shot skills don't work properly, hopefully this log will help (the description I put should be clear enough anyway to replicate it).

[bugReport_20170510_124138_BST.zip](https://github.com/Loreinator/Shuffle-Move/files/989608/bugReport_20170510_124138_BST.zip)

**Comment by Loreinator** [comment] 2017-05-11 17:04
Implemented what I think is a fix for this now, can you check the next development build?

I took the code used for barrier bash + and block smash + to adjust the code of the shot skills, but forcing the number replaced to always be 2. 

Regarding the multipliers, the "MULT" indicates that the last 4 numbers are interpreted as the multiplier used instead of the multiplier. The effect definition is:

`STRING EFFECT_NAME Odds_3match Odds_4match Odds_5match Multiplier Level2 Level3 Level4 Level5 Designator`

Multiplier could be either a number of blocks (Quirky++), a score multiplier on a match (power of 4), or a score additive on a match (Heracross). The Designator defines what the LevelX fields mean. ODDS states that they boost the Odds_Xmatch values. MULT instead makes them replace the "Multiplier" for those skill levels.

So the correct shot entries are:


```
STRING BARRIER_SHOT 60 100 100 200 300 400 600 800 MULT
STRING BLOCK_SHOT 60 100 100 200 300 400 600 800 MULT
STRING ROCK_SHOT 60 100 100 200 300 400 600 800 MULT
```

**Comment by Loreinator** [comment] 2017-05-11 17:05
[Shuffle Move v0.3.104.377.zip](https://github.com/Loreinator/Shuffle-Move/files/993835/Shuffle.Move.v0.3.104.377.zip)

Try this and let me know if the issue is fixed

**Comment by Manitary** [comment] 2017-05-11 18:44
It looks like it's working correctly now

**Closed** 2017-05-28 15:54 UTC

**Comment by ZeroRin** [comment] 2017-06-03 10:24
![dwqnmi 5l3b wg 2y](https://cloud.githubusercontent.com/assets/14952735/26752749/b9c502dc-4889-11e7-9384-12adf4617fba.png)

still not working i suppose

**Comment by Loreinator** [comment] 2017-06-04 00:21
What's the issue? 5 blocks removed. Should non-support species removed be counted as disruptions?

**Comment by Manitary** [comment] 2017-06-04 00:33
It should add extra damage (200 300 400 600 800 MULT), my guess is that it doesn't work because I copied the code from Quirky+ and that does not include calculation of any extra damage.

**Comment by Loreinator** [comment] 2017-06-04 00:52
Try the development version, with the fix for the multiplier handling added:

Google drive link is: https://drive.google.com/uc?id=0Bwi_f200YyRqRC1KWGtjMzU3LWs&export=download

MD5Sum is: 5B78742B8C0A2ED70CCE41B90EAB2728

**Comment by ZeroRin** [comment] 2017-06-04 02:21
it works for me now ^_^
