### ISSUE TITLE
Disappearing metal blocks counted as cleared for Mega Lucario damage

### ISSUE THREAD

**Issue by togawe** [Loreinator/Shuffle-Move#50] opened 2015-08-31 05:41 UTC
Blocks in the process of disappearing aren't counted for mega damage, though the simulation will consider blocks with 1 turn remaining as tiles for calculating the points.

Bug report: https://drive.google.com/file/d/0B7WNJ4-QayHlTm4ya1VCZUNFRGM/view?usp=sharing

**Comment by Loreinator** [comment] 2015-09-06 20:15
Fixed in the development branch with commit 100707a7a143891e129bb110812f989abf792d07

**Closed by Loreinator** 2015-09-06 20:15 UTC
Labels: bug

**Comment by Loreinator** [comment] 2015-09-06 22:27
https://github.com/Loreinator/Shuffle-Move/issues/41

Is a duplicate of this.
